version: '3.1'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ilikoiliko
      MYSQL_DATABASE: gym
      MYSQL_USER: iliko
      MYSQL_PASSWORD: 20022005
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
