package com.demo.folder.entity.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
public class TrainingTypeRequestDTO {
    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Unique identifier, generated by the server")
    private Long id;

    @NotBlank(message = "Training type name is required")
    private String trainingTypeName;

}
